// Autocomplete Widget
$( function() {
    var availableTags = [
        "Abonimation",
        "Agent X",
        "Agent Zero",
        "Ajak",
        "Akemi",
        "Alex Power",
        "Alexander Pierce",
        "Amphibian",
        "Angel",
        "Antman",
        "Apocalypse",
        "Arcade",
        "Archangel",
        "Armadillo",
        "Avengers",
        "Banshee",
        "Barrcuda",
        "Beast",
        "Ben Grimm",
        "Ben Parker",
        "Black Cat",
        "Black Panther",
        "Black Widow",
        "Blade",
        "Blizzard",
        "Bulldozer",
        "Bullseye",
        "Calamity",
        "Calypso",
        "Captain America",
        "Captain Universe",
        "Carnage",
        "Cerebro",
        "Chameleon",
        "Changeling",
        "Charles Xavier",
        "Cobalt Man",
        "Cyclops",
        "Cypher",
        "Daredevil",
        "Dark Phoenix",
        "Deadpool",
        "Doctor Doom",
        "Doctor Octopus",
        "Doctor Strange",
        "Drax",
        "Elektra",
        "Fantastic Four",
        "Gargoyle",
        "Ghostrider",
        "Gorilla Man",
        "Green Goblin",
        "Groot",
        "Guardians of the Galaxy",
        "Gunslinger",
        "Hawkeye",
        "Hellcat",
        "Howard the Duck",
        "Hulk",
        "Human Torch",
        "Hydra",
        "Hydro-Man",
        "Ice Man",
        "Iron Man",
        "Jack Power",
        "Jene Grey",
        "Jessica Jones",
        "Jigsaw",
        "King Pin",
        "Lizard",
        "Loki",
        "Luke Cage",
        "Magneto",
        "Mary Jane Watson",
        "May Parker",
        "Miss America",
        "Miss Marvel",
        "Mr. Fantastic",
        "Mystique",
        "Nick Fury",
        "Nightcrawler",
        "Peter Quill",
        "Pepper Potts",
        "Professor X",
        "Punisher",
        "Pyro",
        "Rocket Raccoon",
        "Rogue",
        "Roulette",
        "Scarecrow",
        "She-Hulk",
        "Shockwave",
        "Shriek",
        "Silver Fox",
        "Silver Surfer",
        "Spider Girl",
        "Spider-Man",
        "spider-Woman",
        "Thanos",
        "Thor",
        "Thunderbird",
        "Titanium Man",
        "Ultron",
        "Valkyrie",
        "Venom",
        "Vertigo",
        "Viper",
        "Wasp",
        "Whtistler",
        "Wolverine"
    ];

    $( "#choices" ).autocomplete({
        source: availableTags
    });
} );

// accordion widget
$( function() {
    $( "#accordionWidget" ).accordion({
        heightStyle: "content",
        collapsible: true
    });
} );